# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:9uXeJ1uI/eptZQYEXqaMAHr1csbO/a+Cz3mfMZznbPzukVV3zi1lJ4DB6o+VRzbAdNca3hPckD/NWqY7XxvIfgFYbdEVvZeRaUFHRd60IKbpaG5Bff2g0mpMsIkzc+w1oir0PaqXpGZVmHE6lAurSSkSfmSxjNA8L968c9m+nvCI9STLdEmsqXjj8w3itmjozp4dNerP0bd8LbT40Pgr3F75yNlCnvHPy6G8/Z5isg==,iv:dctPbVY7Mrvvmk1UohhKJCaHUkyPTCgnOXk53tbBlJ4=,tag:Z5v5AJwPjKvGl/lpzvvSjQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1y0kzuf0tn94a74whazwae4r9qal4snuqfuhl5jacscrpr7up5gts74fe5w
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUTQrT1RVdlVaZFA1eVM3
        Tk4xZ3g0QWVZYzRRS3hMZ0JDMFNmbnprUERFCnJCL09pUjNFV0NqQW91NE9OcDFX
        ZnZHUFBHWnJCNWNFdURSL1BESlFXbTgKLS0tIFBNWVZQSDZLY21TZ2dtV2xsZ2U0
        eEV2aW11K0NEMzdnYWJ5aDlTWHFhMWcKqpYRcxjIllh5LDnN7TWLE3qTeRk8AVlP
        qUsUD1viVHTSMwGs/T9/fYYLanNnckvzrMFbGyaewMNBj2vMW/ryIg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-03T09:46:26Z"
  mac: ENC[AES256_GCM,data:SqBPavbL6Mhp5QrhyGpxaFXXZ0oVBjgDg91RccR9TDsVf24ZlKz272tBWSgE1Z0GO6qNt0a+RArvkBQkeAf4sO9VWJeZZm53+9hIeRlLSetZHnkheWp3dMKgD+8B03coAvDrvl6RbJpqUkfb+17D3MAgwLiX1K2/XLYUbCRPGgE=,iv:c5vPBK2bneg4T4hFVQNwhKnGrk50kD3jOKPU1NIH9R4=,tag:zIUReG1LnIbIENOA+n+lhA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
