# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:fuTtqDR9YlmNe4g7Etb8S2jma4YTtzerC++xnXN3U4hNCU18QUUXIcdCchYRd6CsL2ecFrQFgC3LxVHNIQM6nf3IIHzxs+LD7ygmls2TIq7h1+2nGapfFWgBxku6yaFQgtXgBBgZOaxCidayhxsfeiVEkcSlKsqSau57+6yjuPbG12VrD+Hq57A/4GFOimqy/c5+sAu2hIW+kzHS4tNn3iAiIgQzM8pOGf5QYtUxDPoXqpW1jg==,iv:759epeoN+YEgo1AxNm+8nOkGLJP4JWkxwvi/0ZNoqI8=,tag:zTWeode8JHFXCHxT1ZIXvg==,type:str]
sops:
  age:
    - recipient: age1y0kzuf0tn94a74whazwae4r9qal4snuqfuhl5jacscrpr7up5gts74fe5w
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNHVpaFFsc2lFbzhKYzg3
        Qk1yci84d3cyb1czcDBYWldlSjd1TGhqYTNrCmdDejd2cDRPVXE2OTZKVGtrRWkv
        cHlSV2Urb1VIZTMyNTI0a1pBc3NuVlEKLS0tIHhpN2cvZnY1bWpGTEF6YmEyZVBu
        L0xwTVBWb0ZEWFJoS01OSDlNNk9PN1kKh8IuncVOVupJ3aLkgUebIFl8sThG6mhF
        aKEEm3XB9IwHcuUbOzhJmo5LfSblRdnetrsOfG37NIU8nRwm9D+uwQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-10T09:21:24Z"
  mac: ENC[AES256_GCM,data:lkos4KgydS528Qo5WP0aqUAqyuTm2lC94MAw5pP3f0DQCUxYdl2HEfLLZp4vDSCrEg+XMfZD+L/fX8Ozk6x8wXGO4H3mk3W4dm0i9MN1n8in0ER3hzf6aDIIxIlc5MLV41aHHk/UDkBRhzS8hBodMT7PE5YNk9UMIxBiPJM82VY=,iv:YE7KURxuvXX0A7e/9m5OnAVhxl0YPMJlKmiEJJTSs8o=,tag:DWyu7l0AaKfJklhaaY9/bA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
