# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:4ww204/yx8gFhQNyhaiNO7HywykcfIl4LzQCIoRoNKkWqkyJxdVHvCmppyESn0Fop69fecZOwu632AEB6CPtla1lDeepfbd/hZFzkycCy00Mlr9mtwPsWak7V5xYVqxUKKofbRwJpcDwYLTwniI1ZaIiovcsHTs1PUEOUf4iP5/oi3qJwP7M4cVJDzv8CtdYE+E+3F7wqpuxvJTIZYTLYAJM0qdgIkqytpQBlmVWqg==,iv:CrODNZyh3DrvsxKyOrISoFUXxnUlaexc9jinc6DowyM=,tag:UW+yOURCzXFu+R4ZGjHZ6w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1y0kzuf0tn94a74whazwae4r9qal4snuqfuhl5jacscrpr7up5gts74fe5w
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZWVoang1WUtSdTdjems4
        WjBya3VORXgxM25qd1JkbkxYUnVaSGErdDNzCjZrOVZDaGpSMjJaMURuYmhkS0lW
        WE82Zm5kdzNEMGZuUDBKM0RvS2hzWlkKLS0tIGhNcG53RWlaMjV2ZnN0ZStSdXlO
        VEJDYkdOYWVDVVNWNlNxNEFpL1IvZGcKLxSCSk2MznejtFJdJ3Grv4ozE0VFvlo/
        aH7nfVYAT3oICKl28XLm7cY4gHdDWe2lGoUoQCiMF2zSRydoyt6ATg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-02T20:48:25Z"
  mac: ENC[AES256_GCM,data:H7ejC2lgTReqGKqG9OBowEQjhqkMNwgWtqisNGOOOVxQSJrCVwqH1bJ+I1mfzrmxxviigP5PVRypt4I8MfFZ4fyBjJxAlPdVOoMOLMShh4v0KXymF3t1p2rN9raxrNrE2DQa+ERTpW9Zk5oR3Mht1b4TMDdWteZKeMCuiwJki28=,iv:KezQVp5cDhMuCgICM65e44iP7A3RG7XMpnDOCsQ5ODs=,tag:hR6xd3NdD+/tTZE0cK/okA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
