# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:MWYxpxxeKPtqeFTnWny9+pRLNMsDxWyQrmvLdHhtQl9knAqn/l+snA==,iv:9JrzXe9bIMFasnvhYTDZknRxctrDN0A9K1jUb3pj1X0=,tag:wlnJpxsr7PRVnSLBBLZ6Cw==,type:str]
sops:
  age:
    - recipient: age1y0kzuf0tn94a74whazwae4r9qal4snuqfuhl5jacscrpr7up5gts74fe5w
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRUcyT1NLUGhucUdKVWlE
        R1FwOVlwNlY5dGwzRWpaWWRVN01BTzdMM2hrCnNMTEI5SkdGMXlnYm8vUVNsRGhN
        WHZDQ3c3QUhHeUNuK2pORDRYOU9KOGsKLS0tIHloemhVNXJ6Uzk5WldCWG05L2Fs
        bUpzRzZwWVZiYndkUlZZV3NiaVBqREEKYAQwu8oKDViUfIRJbVjwUeSMMwpTlh4y
        WWuM7shn5nFOIzMQDJpSsbEblE0Ee8ZHBSdtBLdZMI5T/Z/oc3aQPA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-10T09:21:24Z"
  mac: ENC[AES256_GCM,data:MdgGyS5GRNnoy1EKn1rm1SoGKGWfMipt3NwzEtpqXpee/HqW5kuxkdDnXSK/KfekipyIAq05VbthCrn5Dv13CuFj3ewJYLIthrkjafsPyRHpSk44ymjWaz1PwCuEEgeKkCFtCzrmdWKco2Iv8C7Hk3dNwrQO7xOIJvZVzIffaTE=,iv:eZxopt/O/XNLlUuCOfGNkoANfUwsMlMavPd5MsNLOLI=,tag:2JY3DbjYIFNCrbQuPgZMAw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
