# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:+3KntECSGCHRFC+F54S/mhfZi99uJBvstYlrBAXz/MbKHs1vYMnFJg==,iv:LROmwXBi9ozmIgc4gOVUqMyO0B3rjNFGL73oOrkdTuk=,tag:NMhUBVwTX1f0e96rSKho7Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1y0kzuf0tn94a74whazwae4r9qal4snuqfuhl5jacscrpr7up5gts74fe5w
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTFNqUFlVK3B4ZFN0aHV2
        YVhtSTlwVk02UGJBTnNmd2NOa0xMd0FLRWpBClQzaFpLT2s0NXNGWnVEbWc5MkpP
        Qlk1RU1tN2RnY2ZCRHArZDdtZFl1UEkKLS0tIEZSMzU2QUhKY1lIRTN0T2lPWWtr
        TDU5VFpHMFlFUkx4YjdCM1NMazVFS0kK6XdEZHHwoNuouaTCbVkoCZDgFlPnivu0
        mgL5QHJjfd9puYTr+/tCUd1WGA3Rbw/LkO+HOu32BmiMbe9m5b7s6w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-02T20:48:25Z"
  mac: ENC[AES256_GCM,data:JGujVRESEIKZdrs+ob8QXLv+Ynmeyg1iXVuMb5vxIlhWeXKMWwzWAa0XXqkEUbsyG4RV9BmLpOF/X2gAGqlXaED23em0j34gS4F4b5s++MfjiUsEwIHgV9TPiR8GnwU+YYyfWAfV8SDlRMWKnYXvQh/kQs/m1OcCYVJ1T7RSoRU=,iv:4/CxiN5uMpE4jn4KC2qxFnFVItl3o5Y8tJohvK7Xly8=,tag:Jqe6RvR0glPwKPOAXnOAGQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
