# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:9eMsXFItQLIQPDecPDCPbOIWIRQ62uiviXulCTQ3AKYo3MswCbqEeQ==,iv:oNGhi9lIVopicdcseQAKbPz3AUBQibQVozcWcJa6vA0=,tag:dCVbo2TnKnSskaj6onm0yA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1y0kzuf0tn94a74whazwae4r9qal4snuqfuhl5jacscrpr7up5gts74fe5w
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZ2hxYnZzSFFLUTNUUlJI
        K2hRajVzckRodmorY2JGMEVmM2xGdWlkeFNZCnRBb1N1TGFabEo2OTVHcjNhNGhO
        aXd6d1FHeExmSFpINWdIMkZzckFwdFEKLS0tIHJUSzN1bGcxQ3BaUE5SaTVPQlF5
        MkJyUUNjb1RIVjhXb1FxcWRnbUo1RDgKlXuVfF1ndft+cwdYPYceinQGIsDSMb68
        YEz7sm9qnPpRIP8S/MpzbE4c4gs0jmDb/fSqqhqvOQWbb1MuiU8qvw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-03T09:46:26Z"
  mac: ENC[AES256_GCM,data:Se585fwF4VGGhqAHPGQxNBRZJGHcHVN/fKNrCfpzjGVd/Bs1TTUqlP2a/jJ5LPk1+iKAKsIqcQ4SUDje/1rsbVOYUQvLnhvxgSN9oDsmJPy2xaLztbJgVE2ARN+ufLYH55d5VzwSedQI+EHTMJ1Mla/+rQH1f0XJrANy7aLa/2k=,iv:6SzH8wdXaxfZZm7sH1n+D/ZKvRRU2BZPQtyX63p+riU=,tag:5+6TwOS7/fzkz3Nn45xr2Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
