---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clusterexternalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: ghcr-pullsecret
spec:
  namespaceSelectors:
    - matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
            - kube-public
            - kube-node-lease
            - flux-system
            - security
            - cert-manager
  refreshTime: 1h
  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: onepassword
    refreshInterval: 1h
    target:
      name: ghcr-pullsecret
      template:
        engineVersion: v2
        type: kubernetes.io/dockerconfigjson
        data:
          .dockerconfigjson: |
            {"auths":{"ghcr.io":{"username":"tuxpeople","password":"{{ .password }}","auth":"{{ printf "%s:%s" "tuxpeople" .password | b64enc }}"}}}
    dataFrom:
      - extract:
          key: ghcr-k8s-homelab-pullsecret
