---
kubernetes:
  children:
    master:
      hosts:
        tpi-node1:
          ansible_host: 192.168.8.111
          ceph_drives:
            - /dev/disk/by-id/scsi-SATA_P3-1TB_0009478001268
        tpi-node2:
          ansible_host: 192.168.8.112
          ceph_drives:
            - /dev/disk/by-id/scsi-SATA_P3-1TB_0009478001526
        tpi-node3:
          ansible_host: 192.168.8.113
          ceph_drives:
            - /dev/disk/by-id/scsi-SATA_P3-1TB_0010163007425
    worker:
      hosts:
        tpi-node4:
          ansible_host: 192.168.8.114
          ceph_drives:
            - /dev/disk/by-id/usb-WD_Elements_10B8_57584131413834354B464555-0:0
# nfs-server:
#   hosts: tpi-node3
