---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/traefik.io/middleware_v1alpha1.json
# Ersetzt nginx.ingress.kubernetes.io/auth-url + auth-signin + auth-response-headers + auth-snippet
# Referenz in Ingress-Annotation: traefik.ingress.kubernetes.io/router.middlewares: network-auth@kubernetescrd
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth
  namespace: network
spec:
  forwardAuth:
    address: "https://auth.${SECRET_DOMAIN}/api/authz/forward-auth"
    trustForwardHeader: true
    maxResponseBodySize: 8192
    authResponseHeaders:
      - Remote-User
      - Remote-Name
      - Remote-Groups
      - Remote-Email
