# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:DjzQckFsIkQWXXuMPvopyiN31UBD/CVTLerYjgUU+50=,iv:Q/eEJ8Jlmx7IBpEQB82uDz12nIpT+TO+jic3cSkcXYs=,tag:+PUKx2W6VlVdpK73DvW+Ww==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1y0kzuf0tn94a74whazwae4r9qal4snuqfuhl5jacscrpr7up5gts74fe5w
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYXBUZTY1Rm1RTExpU2Mz
        VTgwcXNGL1NjMGFFYjdCdHVOQXBPdFU5bmtNCjJJMDY2cTcrYUcvcFBGVW52WEZN
        M3JZQ1hIcGwzcnU4Zi9nTXRyKzF3OU0KLS0tIFdCVm94aVBkYkhKSURmbExFRjFs
        Ni9lMk5yVEs5bjdYUXJTVmIwL2pCRncKl+uyyzDSwNTltGHOCl4GLHnPLMCdG8dc
        0pksrN5CGDKH3UQyxfcg7WfPhQiWxSb5Bx6pHPcdJke3QgZxJoR6pA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-02T20:48:24Z"
  mac: ENC[AES256_GCM,data:Oy9bKh51lGvR804hHlba8VANhPep5puSG3WXJvsiRxJAW92Hei/hBSpzcY8VhATKIQukJf5Zm84/fZV+zlwhHxGQb8dIg0PoxZnL77iLij1KQwQNNHQUdLmAtcC4v35WmlF1U6dAlR+yTPma+v2hfa2VHLsBbw/YghW6YaEyLD8=,iv:IcVSHWAdMF4g4/OZl5VQE6HAdTop93P+ZZg1w0eFEpo=,tag:yucuzdPB1Ib4gb9hChT6yQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
