# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:UU+OEUJFKeWFWmA8ZS1Z8QmrJsLKabd5UwG1xMJuQLk=,iv:nex9Q1fzDhT0S45inwiTHd2Oe60SDcbbNDvkDdO/euU=,tag:SSKpzDQq2ls7BapH6k7Qbw==,type:str]
sops:
  age:
    - recipient: age1y0kzuf0tn94a74whazwae4r9qal4snuqfuhl5jacscrpr7up5gts74fe5w
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWmZMMzVlZlduQTFzdDJp
        ZU1FaEJldS9iSHlOTTJvRGdDcUh0VTY0ckhnCkdlcnVvekVFV2kwUEh4b0xrdlRv
        cFN0MFNDUzhXSjlZS1IvdjZ1Rmc4d0UKLS0tIEd6dHoydlVZUzJVYkVHeUs0QVFY
        SWNZTUg2VTdzWjV3cUJNNXdMZlhSVzAKCHqOn8xREGt3GFpJBjefIflBXzONVIEt
        hPFxVz+unVW9jePzFWH+sO4GmDrWUFioR+TNdNlfUw5NnoLIsgMORw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-10T09:21:23Z"
  mac: ENC[AES256_GCM,data:tGaKUq5bCmkOtK1Mtvs4eXAqdLsOwqv0Mcmj0TT0ZyCVWG58oDz50k9WUNl641MtsEAFSP7kGSXmS7mQNDNsRqFG4TkLhJdJyl/rzuzw29Fii7cgb5PN2g6kn+KcmikAYrR3TdY/PwohUeP4YtebKzwlE3elOPb4jbwBdtafSVk=,iv:zr6iK7lzuGpW/HNpzDMq3WHiU+NlAO0Vfzexv3Hb3PY=,tag:VqW9jxRnpo7zNqFzmTiONA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
