# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Lk10PmOSSvCHKvqRftnQdFvsiIYk99dBQ0lU6Sf6+IU=,iv:c/wj24xdwbmRwRuJPHPbiZr85dKjKki0nOdgm1bKfrs=,tag:ElEWD6eqakHB/msmopTUyA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1y0kzuf0tn94a74whazwae4r9qal4snuqfuhl5jacscrpr7up5gts74fe5w
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBteXMvVlU2YSsyMXhRdGZ5
        bnA5MVJOWXhKczdzUjRHL25wallIQmxITEFZClBzUUVyL1hWVE5wUmNkWmpBc3BL
        bk52aElpZ3hBeDZzUit5b0Jwbm9JczgKLS0tIDJrZmtQdENsb0FoeVo0dHRuR2NW
        Q203Sm9DalVCOThyM0tpc2o5Mm1GTFEKhCpc9R9HK01wLmF+zRF+xnxMAtCDLi1F
        VjtB+wmccHerIZuTGpX1t4xTrk3nE8mzazFrwrM/Wu3KsWzlen4n0w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-03T09:46:26Z"
  mac: ENC[AES256_GCM,data:xobsEuq7nirTMFB1CldpGEi+rXl0jr9Pz7WNsHTbgSee/ygmXsIad+87bCCY4EL/L4mV708ZGr1fAFrxITYWojNzVxaX3o63BJeikmUh/kd6xZ5y6Qp0HGq31DhT4fzeBYCuidOkwJ2gzFF+qI/Qk55S7pfVnTLwpHQ1NAIIQCM=,iv:lobUwOqtSHrFAzqwWqXoD6Wvt9zu8Tc2Go+YPTF05e8=,tag:SRETRPAna8pdWYm7ZpQKOw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
