{
 "title": "MyStrom",
 "tags": [
  "power",
  "mystrom"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DATASOURCE", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Current power consumption",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mystrom_report_power", "legendFormat": "Watts" }
   ]
  },
  {
   "title": "Current Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "crit": 1,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "mystrom_report_relay",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Current temperature",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 7, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mystrom_report_temperatur", "legendFormat": "°C" }
   ]
  },
  {
   "title": "Status History",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 5 },
   "targets": [
    { "expr": "mystrom_report_relay", "legendFormat": "State" }
   ]
  },
  {
   "title": "The current power consumption over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "mystrom_report_power", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Current temperature over time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 18 },
   "targets": [
    { "expr": "mystrom_report_temperatur", "legendFormat": "°C" }
   ]
  }
 ]
}