{
 "title": "Octoprint - Print",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "current_print",
    "query": {
     "query": "label_values(octoprint_print_progress, path)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Printer State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "octoprint_printer_state_info", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Total Started Prints",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "octoprint_started_prints_total" }
   ]
  },
  {
   "title": "Total Completed Prints",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "octoprint_done_prints_total" }
   ]
  },
  {
   "title": "Total Failed Prints",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "octoprint_failed_prints_total" }
   ]
  },
  {
   "title": "Total Printing Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "octoprint_printing_time_total{}"
    }
   ]
  },
  {
   "title": "Current Print Progress",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "octoprint_print_progress" }
   ]
  },
  {
   "title": "Print Time Elapsed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "octoprint_print_time_elapsed{path=\"$current_print\"}"
    }
   ]
  },
  {
   "title": "Print Time Remaining (Estimate)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "octoprint_print_time_left_estimate{path=\"$current_print\"}"
    }
   ]
  },
  {
   "title": "Print Fan Speed",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "octoprint_print_fan_speed / 255"
    }
   ]
  },
  {
   "title": "Extruder Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "octoprint_temperatures_actual{identifier=\"T0\"}",
     "legendFormat": "Actual"
    },
    {
     "expr": "octoprint_temperatures_target{identifier=\"T0\"}",
     "legendFormat": "Target"
    }
   ]
  },
  {
   "title": "Extruder Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 9 }
   ]
  },
  {
   "title": "Extruder Temperature Difference",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "abs(octoprint_temperatures_actual{identifier=\"T0\"} - octoprint_temperatures_target{identifier=\"T0\"})"
    }
   ]
  },
  {
   "title": "Bed Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "octoprint_temperatures_actual{identifier=\"B\"}",
     "legendFormat": "Actual"
    },
    {
     "expr": "octoprint_temperatures_target{identifier=\"B\"}",
     "legendFormat": "Target"
    }
   ]
  },
  {
   "title": "Bed Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 14 }
   ]
  },
  {
   "title": "Bed Temperature Difference",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "abs(octoprint_temperatures_actual{identifier=\"B\"} - octoprint_temperatures_target{identifier=\"B\"})"
    }
   ]
  }
 ]
}