apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:oKzG+pZB/PIe44YLQmMY,iv:/smCCNy0Pw0WeSIrDC1XtQ0BxVrVTmbk09S7uzjm4is=,tag:mRMg+DX/g4OPcn0cemDywQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1y0kzuf0tn94a74whazwae4r9qal4snuqfuhl5jacscrpr7up5gts74fe5w
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSitQV1ZOR0o1Q2pFN1hz
        K0VOU00yTmdNNk5pcSt5ejFlSnlQTWFzdGwwCjcybDBRZGJzUFFQVHY3SG1Qd3Z4
        L0tNd3RjU0xWQkJhUmdpVmlsZWcxRncKLS0tIG0veWYvNTlCNFh1RlhDeEVaa2x4
        M09mcVI5UDJTSmFOMFNEaGxqK3puNzQKBQqMfgpXFlA48ezleaQhPke5YCLJUQWi
        fe1OcUXeG9dLNfbZmq71EARUBj9YRicbtWcy1yW4vCOzK50eNt2bOA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-02T20:48:23Z"
  mac: ENC[AES256_GCM,data:d3HQVmLzR2ktNJeY56UDiaNVei6bYExV+lAheP8wyYJpV6W1KCNQPO3rL3fUL/j3961rkdGsJ47J/wAhaFmx88ZzQXa060KxZDPvlVmRZpI3liicf7CWsQppBXl2LvU5s2JS+Laqr7bY6WmT8wl47v5R/E7k567X0GnVFgmUp6o=,iv:/c9NVhW+/ToawbvrVqIHtqJmHDxkhEFFJk26Nyj6dw0=,tag:uz9rN1d+TQuxU6i2R/Drdg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
