apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:7zEL0DprXDV8hxCHJcS4,iv:V3F6ZUKSAEZ6lkl1sX80ax5mc4ZYVUVJpeZCHq2twaQ=,tag:CXXyyA+GMSFVcdf2mxhjEA==,type:str]
sops:
  age:
    - recipient: age1y0kzuf0tn94a74whazwae4r9qal4snuqfuhl5jacscrpr7up5gts74fe5w
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbk5OenFaV2pZVVIrVXR2
        SkUxZUtWalNMdVhUWlRPUkloY2kyOGVLUFRBCmoxYkg0ZUZhdG0zUHAwZDI0aUJx
        bVR5blMyYXN5RFFRUlFoUFk2aWFHTlUKLS0tIHBEeVRXc3lPT3gyMnZxUVVrOElu
        NDBJRWxSV2w3MDZzMWc5ZzJ0WlNYMGcK+g3LFPvWjCTjiVs4LYH+DNNSjRPKOkpn
        XTC8jYMSfTPik+G7KDkTDO8UFnud8t0aDnvE8iD4+CIBV/480z9Olg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-09T16:56:17Z"
  mac: ENC[AES256_GCM,data:sJE15hA2PH0GQPe3O8qszBT7bdavZxoiqEZ4g41JEwGEiBG6p61xUBuvNzTMWyb5gRR4LKr2XGpmt6BY1Hp3ENn4usE08ypmgo/jyOb+FOdZ7FfDzEcAfdDHtRCGRVVF2DsOjOkKn1Gxta8bOm4a48nn1ZXioWiUS+R6bf7v+Oo=,iv:R4PHC5JcD7zxztIYpa90k/sPJLFw7jGbGqIN+2UNN1I=,tag:HwRqhpJrc32SKAmwtnpszw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.1
