apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:eJ2+6OrxbhKLds1VZ35Q,iv:Y7GGS4+ZwHoOdIwbEQGVGVFP+WDHpb3M/pFku2NamPQ=,tag:RTJzp+2braeXu1Ibxzn02A==,type:str]
    SECRET_PRIVATE_DOMAIN: ENC[AES256_GCM,data:vHqEvA==,iv:y6AQtoPV7YZcd9Iw2XpBAMk47vBDEm6L/n15ebX8Tqo=,tag:nkGclLdaTQO11LieJxtweQ==,type:str]
    SECRET_CH_DOMAIN: ENC[AES256_GCM,data:Qc/gCAi/Mxlb+FQ=,iv:uHwuKAoLdN/Pn3gN2USYwpPyRHiTKxaNGx3XA7FDp7k=,tag:/6zZ2mfkELa5RE1YUCVeUQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:wGTKhXSbhUvNkVvjJw+663rvQUU=,iv:Ov38frgRp4MK3HenswkUFZlFr1TeP6Jqu8E9VUUaodQ=,tag:Kv/w3WlKuRSua1UHv40hJg==,type:str]
    #ENC[AES256_GCM,data:VcxksSrE,iv:lUiWbl3M4Awf3nFXCuSqR+ST4nC+0xz7MI8AwR86XeM=,tag:HQ6wZQ6gpu0I62Pm42T4Dg==,type:comment]
    SECRET_MINIO_BEARERTOKEN: ENC[AES256_GCM,data:ZZH03tQF3XuW03KYAYy8OlF3xQGyxnZr8pPlcoUB72XNdpi1gEM8kH1iHFiKcLmfO5jwIAcN0OckKhwoeyWNWYRzym9LUBlotMiyUeExbBF7l9RVGOLS1EboK0hIKpQqcpky9+Oj5Z6z9RY6Q0RBbBxVeTFJrFVT0x7XyzemzNo7IfLqpXmi7ElFqNRWEsRfxV0n30U9AVcfLzmgOxBOQAcmLIy72PETt1bXwgYGp7a/GfPJreJ2VQZNP0/2WlhN,iv:XQ1kHPITUQtSjGx7XwV7x7UWJ+oR4D4nzOPkRKfdkoY=,tag:GIs0ZqHzB6JYAeotRpxlAA==,type:str]
    #ENC[AES256_GCM,data:67TmHEDs9Q+Agww=,iv:kQvgHhVyDGjZw11CgZui7NYu6f3E/Vv41vz4Kj5aoSQ=,tag:yMerwS8Rh6ZbdcbaxycGOQ==,type:comment]
    SECRET_ALERT_MANAGER_DISCORD_WEBHOOK: ENC[AES256_GCM,data:WHm2F0XXHXU+BNYkleY83faq7VVfUlkaflzWPLdc+lGr2kiEqSEvCG24OTjNSNJd1EV/xSvrOooRvNbsI7/hYDVxwJ9J/nteyuhrpd7aXO9kjZj+4M2Z/KEloveumsXhJ1HStDgZKwMQVIRVTCn1oj/Mid8noZ/gnJA=,iv:x6ORrI39QXVfgpaHcu47f34ae+czOnC6x/Xnob/8qWU=,tag:8g2T3K04oqyTl+SRNYX0yw==,type:str]
    #ENC[AES256_GCM,data:k++ccsF11szB,iv:ywXsDnikeYOJWTMkVKn0SnMAaTrWcAiwywKVeFSorOI=,tag:SMmjkmq5vvmX00ZmfIrKPA==,type:comment]
    SECRET_MEDIABOX_IP: ENC[AES256_GCM,data:WoMCSHZPUiPNFyk=,iv:H8meTBNVEc0vLxjy4PHcfdBtDERWD+yJ7mcoKSSffto=,tag:CaHb1pMi099Knyeq1Y/GAQ==,type:str]
    SECRET_PLEXTOKEN: ENC[AES256_GCM,data:x3lIZGqk2XszhlWuqUmFN7HWmhk=,iv:JRSy+UXaWrEryUdD3CzMe/aUVMUDxhAoLz3Hmb42awA=,tag:KnDKBNnD849pft982lh8rg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y0kzuf0tn94a74whazwae4r9qal4snuqfuhl5jacscrpr7up5gts74fe5w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSUdzM0NCQ0RKcTd0M0V0
            N2h6bEJJY1I5UFN3bFppc2VEbmh5NTVGM2xzCmFwSStaM3ltaG1oT2ZzUjAzaVc4
            VDZibkdUT25tSUFselJ6M044R01DNncKLS0tIEZXVjVHRktGVWpIOUxEcjMyNElv
            OEJBZUprUlFtaFdIQ1FMRkcybHVaQzQKpD4LGrp04agBhc0CIskz6YNOk2fMcB+P
            9Im32oMk1njeXcdwfY683FI4OKUpGY+1aodBePbYCjdz6D+HbLOZ7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-03T11:39:28Z"
    mac: ENC[AES256_GCM,data:44Ki2EGgFupqmOOluo26tpGQjQ9dYadAYP+nVAQfzVxY4USBIKZoiK47D1lHPgONkORyXr7CraR3djzNJN6OoBZ0NHcKlhF73UtK3Eyt7NO831p3609npE+GZF64pRYNsebzWmrBpdHJz4x18Mcn0Xfut8oQfcLu1l0/wHz2wVU=,iv:7R0fvTJKUhTw9MOClBk3XsSaFIBYM4I3cqHC2Z0jb/0=,tag:zKUdZkPZevqbggj37M+AhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
