apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:Je7/CdGfOQcRQak4gi15oG17Vje7E026qvSFNWEn+SQGb6GzK4o3rgoXd1VeJL94+ZDL52u6HFuHvV5t10fIRjKKt3Nv08rZVi0=,iv:a3cxo4llSuQVsU72XdOH+AzG36klK06Mh0XlLdOJNf4=,tag:GPzE0hfyDXphjDdSt2mj3w==,type:str]
sops:
  age:
    - recipient: age1y0kzuf0tn94a74whazwae4r9qal4snuqfuhl5jacscrpr7up5gts74fe5w
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiYnhyU3IvaWk3dTBwUTd4
        NksyQ1FHZ3p4VG9BWDVyWEFndFN4TkFZa3dnCk4zRy9ma0pEeDc0SXp6VmpCTjg2
        M0NEaGdDYng4Y0Zvbi9IbU0vU1JpQUUKLS0tIFE4VEtDcTduL0lxajQ4VjlTWXhv
        RnFFZkVzazUrVFlkcVRYVVhseVQ1c1kK+NA2WtOD5ILzi6UWbUUEsUYtehXIo0BG
        AjefaLj4/4AiCCQ51eVln47hnkmgR0nwnc8D+jwD0+NAEbLBHv9gbQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-10T09:21:23Z"
  mac: ENC[AES256_GCM,data:0NJxlTIRX3ya2v/tyLPm7kZCXcFkbsRaYxSA/rwWRtQVP9nuCVdLthZ9aeUUHVHWdaKPawwx5xbZSnpdGCcHCyc8J7jNJrsXQaIxNc86rCJTbKEDwhEV5D+SP7/Zs7SIVdPxlj358Mko9PKP7Pa0vs4eKmgu6BAjoqe7Erks2Lk=,iv:JRuJ0+a7VBvF4C3uwiUITHzUc1RopcVte4+szxLJnpI=,tag:raMx+xe9QxqTRXQJ8hLQgw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
