apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:zR8ZkvI+WyxvxfwsTLF8hwuIXrsyxhbP1gwvtsmElnJRQdZka5nyVEIShvv7DcbyD40OPQZxb/nNeqBEOA+CZ+nY8RyDKAnwwO8=,iv:pDujn6iGeI9uznRLhSCoV5Lw/cKEpSh6tE8nxTWPRgc=,tag:wVY+xQzerd3JrWUYD8o1Gg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1y0kzuf0tn94a74whazwae4r9qal4snuqfuhl5jacscrpr7up5gts74fe5w
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMWVvakdiL2czVzVROGkr
        dHZmSzBGWHVzZFJwYlJsNFJmMWRkVXNqaVM4CkZFankxSVZYRFBJL1owM2JxaHVs
        UGFEWW9hSGtMZnExelowZnF2VHIreXcKLS0tIG1tTCtheTQycTUvVUlqZ1ZldXp6
        TUtEQzUyMlhDeDQ1TEppMm0vaHRwK0UK1/2Fls5HaAoRNaj2vKxDx3BqipL9rpm8
        beqgC0jzET1iI2U+EOe1IYot7He6Kg6SZLuGz4bmFpNt1v5nJVDqaA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-02T20:48:24Z"
  mac: ENC[AES256_GCM,data:D1NAfYq+ZoO8kXF4uFnQmJt8o58Yig9bAsfg+R4O8gL8g/1WFss8FjJ3HaXfpjRks1kIYL18W0wwiA5feW1UXffPGKIOFvzbRHcFzqt60dixMu4jeX/qMkmQ2s2xhduvVDkScUcMi2J2luMp0XETUCy8GS70lcdqLJWy4Htpvrg=,iv:UI2VO+6j71xtq+Rn8bcTGcjnFhExi6uethIrd/4hp0c=,tag:qcTQXnw9iQZ5RqZUIMj/1Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
