apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:R+OhHS4Evdh0L0x9zTItGLmAv4RRZ3I7RkimFpWTxL8U9YHS9hnqTNqyxQOhTbihXsjNanwRKh/juDIIVS/HJuFGk47WqFxpels=,iv:TSrQc0CTXFCHeTPFfRa1CtgQ8ktuArl0tAwmWXWI/t4=,tag:3aVppYHhP90ZYuH022Zxqw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1y0kzuf0tn94a74whazwae4r9qal4snuqfuhl5jacscrpr7up5gts74fe5w
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzU08xQzFZenoxLzhTYnBJ
        UWtGZHNEeVgvWm1ibWdaWEQraG5kd0ZNekJBCitxOGNUWE5ad2xmOUFRRDlwZ080
        M3NrOEFkS0I4U2FoTk5LUjJHZXVjWG8KLS0tIDFSS0xlMkRaK3V6NitLODhJa0Q5
        RzkxSllOdUZydHlmbFJzRUZlZmdYbXcKspPgH2QDDMoByAEosjBzj0E9cRutrr7B
        EgjnBgOpvctN71n+3RIel4rcQoElPXpJ+9tRXZpyg1kiMUP2vNafaQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-03T09:46:26Z"
  mac: ENC[AES256_GCM,data:Ab2Pe+doQnYu5rydkJWQ1cNZfssBwPkY4HEC+xm4m4WD+VR+g9lxOilAK0ho213ImF4O0QjZjsoeUOSbDaRrsUNRHpZ28qNX3302k6bM0TcgVrDd+0OGn+x7S1ts+WgwYYwEUyWvpiq0Rm3CGWylPtg/pPGZPiPcjgrSBT0meT0=,iv:R78ue7MTjQTulDOY0Q4qcERowPWOzr06vY9e6p1+2J0=,tag:lCnZfFcAfgO/PsGBajndIw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
