# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:PUZTumW0qPzaJLQfG9R7rPCKayR+o2MEaFRpFswfa1KK+H32127YyQ==,iv:hrCOKzGKyBW1a0vGH1w5+LseZKyXEwDenKxr8/HRFuc=,tag:c6yBwl/wX9696iSEv95v9Q==,type:str]
sops:
  age:
    - recipient: age1y0kzuf0tn94a74whazwae4r9qal4snuqfuhl5jacscrpr7up5gts74fe5w
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBublZPaUNlaUVuejM4WWdW
        bHVndnJuWHNiZmI5WSt1T0VZemtMOUczaGcwCkdFaEhHZG1VRXc5aSs4Q1BWSG0z
        RVJHUnFtU0Uwc25NVEk4eGx1N3M2WFUKLS0tIHFLNGYwUDRxR1J4T1YzaS9wc2RH
        NG5McmRWdzFMR3NtY1lYbDJyTzg1TFkKLHA0wJqOt399L/kFMbKWK4Lkn9eyJKOQ
        B+1EVAvKaA7idNm/N2H7tcdMzSqLd6rRIlYF2imMRWqeA1MhmxcnFw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-10T09:21:23Z"
  mac: ENC[AES256_GCM,data:///JwEafrXGMrbTZ45bO0ODxn1vZHuwrCUMYyAH4cRxTjSru/bzTTxFvpsqOMEIMqdPZiSXi116Yplg5bKDXeQbVGAeXNdowA8PRfDW7e2omXn9pxhfM8ULFtJrMd3PACxnbm7EFOP72NL/NCqsfjL+pRl1kJOL405P8WU5zb44=,iv:hJR9xDlNN4fS/S88iXKoFdHoscDbHFU1ZgzKziupJ9I=,tag:cbObLEWAqMRSFdnYVnokeQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
