# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:PCwulgBYs/j9y3CEqEhntavro6KPVgRlQ5TPyfya+n7y54Me234V2w==,iv:jMRVXSb+zCc/Xp9ZhhoT89Ipyeg0xO6YcljblIb9jGY=,tag:aQQZZVZTyneDvvovjOpRCg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1y0kzuf0tn94a74whazwae4r9qal4snuqfuhl5jacscrpr7up5gts74fe5w
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWDRBSmZOVHpHcjA2N3Br
        amI5NXIza1FYQmVtZlRCcFVHOXZwRzZCbVhJCldGOURQZHdEcXdOQXJ2MEhNZTRO
        NVJvWTRzNjd4VEpWTEYwZytTTDJIcGcKLS0tIDZ0QXM5V3dsYUlnWHdvNVAxbHFV
        N1ZPbW4wWWhMSXlTYWliZmR6Ym1rUlkKa7YxXf+wySg0HWbXXlMsfbX5Gj0TyEq/
        iNiDZg+D8lYxJUwE2zVovbYBDMtkmMppTfpQg3iJjjy7oiozzJSFAQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-02T20:48:25Z"
  mac: ENC[AES256_GCM,data:c3u6yeMeCvuUfQTYrMzP4wqsF3lrJDVqi4vbfHOSerogvAcxxCYLxQcVW7F9AuvXGyRlW8bJl6owvgN+dgUvc1BbXn0lIr8EI+/7BiZjmI90q6NbqFXa9yTOkfybv/39kkdzn32kueNlbmmo7fGdpcKU1Pp02NV0zJaKKOX+buc=,iv:/2beBbeyG2tk9WS4e2gSHNRKHKlN/6yLn1yA8gZc7o8=,tag:kpQeaBJOeo06tQLWu/W2Qw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
