# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:M5oKLN2VKThovinUP5oZ3h77j6xsfoZ7uefeWfx/gfTd5LUHSTD/lw==,iv:vn5oa2tsEzEeDT0HjU3idOo7ZJlKmxZI2DEQ4R8i0EY=,tag:qtTWSZ+SUITa8IXr5tTsog==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1y0kzuf0tn94a74whazwae4r9qal4snuqfuhl5jacscrpr7up5gts74fe5w
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZGRHWGNZTFhLalVjaWtO
        Z0xMdXFVQVFlcWwwMVpxOHVkZW1KdU9SbFhrCmRqS1V0TVNxY09pUlFZZEQ0TG8z
        UFdHdkM0Z1hIL2J6UEJVNm9ETFRQTGMKLS0tIDAycnpmWU04bGN3bGVpUm9xNGlD
        SGYwTWRNck1wOWxsRk9zc0pIOU9JNVUKTWZ2VG9hdDn6sgoTLcHqnJGHD/Iw9YY2
        1+gNna/mgiQqldNNRU3P8itLXKB496tkDh6Q3xjXxc185pXTJ3BqRQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-03T09:46:26Z"
  mac: ENC[AES256_GCM,data:Ym6qWjyLg52o4idkpvt+VI0qiLQ3yxYwQCP893N9LWWixbUDCKDN3mYuGaL7lplbSSjg6HeGeMbS6Ky3aGuJD4+4fpqGP8ksoGWJK9TLiGVL9qyLjLPntmt0uR9+nvW4J1Qc4Q8BwzRvB24qIO6E/JYmES3pxdZ9uG/FwTJjPkE=,iv:6xGKRKI2h2R70eu9PbGONUIOu8IimSXp2CIkh1MKzR8=,tag:LZbtx/epmJ0WHjFuNXJkFA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
