# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-3.7.3/charts/other/app-template/values.schema.json

controllers:
  obsidian: &app
    strategy: Recreate
    containers:
      app:
        image:
          repository: lscr.io/linuxserver/obsidian
          tag: v1.6.3-ls12
        resources:
          requests:
            cpu: 15m
            memory: 259Mi
          limits:
            cpu: 500m
            memory: 850Mi
service:
  app:
    controller: obsidian
    ports:
      http:
        port: &port 3000
ingress:
  app:
    annotations:
      hajimari.io/icon: note
      hajimari.io/appName: "Obsidian"
      hajimari.io/group: productivity
      traefik.ingress.kubernetes.io/router.middlewares: network-auth@kubernetescrd
    enabled: true
    className: external
    hosts:
      - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - *host
persistence:
  config:
    enabled: true
    storageClass: ${MAIN_SC}
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 20Gi
