---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arr-apis
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: arr-apis
    template:
      engineVersion: v2
  data:
    - secretKey: RADARR_API_KEY  # pragma: allowlist secret
      remoteRef:
        key: arr-apis
        property: RADARR_API_KEY
    - secretKey: SONARR_API_KEY  # pragma: allowlist secret
      remoteRef:
        key: arr-apis
        property: SONARR_API_KEY
    - secretKey: PROWLARR_API_KEY  # pragma: allowlist secret
      remoteRef:
        key: arr-apis
        property: PROWLARR_API_KEY
