---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arr-apis
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: arr-apis
    template:
      engineVersion: v2
  data:
    - secretKey: RADARR_API_KEY
      remoteRef:
        key: arr-apis
        property: RADARR_API_KEY
    - secretKey: SONARR_API_KEY
      remoteRef:
        key: arr-apis
        property: SONARR_API_KEY
    - secretKey: PROWLARR_API_KEY
      remoteRef:
        key: arr-apis
        property: PROWLARR_API_KEY
    - secretKey: SABNZBD_API_KEY
      remoteRef:
        key: arr-apis
        property: SABNZBD_API_KEY
    - secretKey: OVERSEERR_API_KEY
      remoteRef:
        key: arr-apis
        property: OVERSEERR_API_KEY
    - secretKey: TAUTULLI_API_KEY
      remoteRef:
        key: arr-apis
        property: TAUTULLI_API_KEY
    - secretKey: PAPERLESS_API_KEY
      remoteRef:
        key: paperless
        property: PAPERLESS_API_KEY
    - secretKey: PROXMOX_API_USER
      remoteRef:
        key: Terraform User Proxmox
        property: username
    - secretKey: PROXMOX_API_KEY
      remoteRef:
        key: Terraform User Proxmox
        property: password
  dataFrom:
    - extract:
        key: homepage
