{
 "title": "Minecraft Servers",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server_name",
    "label": "Minecraft Server",
    "query": {
     "query": "label_values(minecraft_status_healthy,server_host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overall Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(minecraft_status_healthy) by (server_edition, server_version, server_host)"
    }
   ]
  },
  {
   "title": "Number of players currently online",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "minecraft_status_players_online_count",
     "legendFormat": "{{server_host}}"
    }
   ]
  },
  {
   "title": "Amount of time it took for server to respond",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "minecraft_status_response_time_seconds",
     "legendFormat": "{{server_host}}"
    }
   ]
  },
  { "title": "Status of $server_name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }, "repeat": "server_name" },
  {
   "title": "Players online",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "minecraft_status_players_online_count{server_host=\"$server_name\"}",
     "legendFormat": "Number of players currently online"
    },
    {
     "expr": "minecraft_status_players_max_count{server_host=\"$server_name\"}",
     "legendFormat": "Maximum number of players allowed by the server"
    }
   ]
  },
  {
   "title": "Server response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "minecraft_status_response_time_seconds{server_host=\"$server_name\"}",
     "legendFormat": "Amount of time it took for server to respond"
    }
   ]
  }
 ]
}