---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./gatus-external.yaml
  - ./gatus-internal.yaml
  - ./helmrelease-defaults.yaml
  # - ./ghcr-pullsecret.yaml  # prepared, not yet active
  - ./ingress.yaml
  - ./limits.yaml
  - ./ndots.yaml
  - label-existing-namespaces.yaml
  - reloader.yaml
  - require-storageclass.yaml
  - restrict-deprecated-registry.yaml
