{
 "title": "Plex Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Current usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(plex_transcode_sessions_active_count) by (container)",
     "legendFormat": "Plex sessions"
    },
    {
     "expr": "sum(plex_transcode_sessions_active_count) by (container)",
     "legendFormat": "Transcoding sessions"
    }
   ]
  },
  { "title": "Sessions history", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Active plex sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(plex_transcode_sessions_active_count) by (container)",
     "legendFormat": "Active plex sessions"
    }
   ]
  },
  {
   "title": "Active transcode sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(plex_transcode_sessions_active_count) by (container)",
     "legendFormat": "Active transcode sessions"
    }
   ]
  },
  { "title": "Library content", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Numbers of TV shows",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "plex_media_server_library_media_count{type=\"show\"}",
     "legendFormat": "Library \"{{name}}\""
    }
   ]
  },
  {
   "title": "Numbers of movies",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "plex_media_server_library_media_count{type=\"movie\"}",
     "legendFormat": "Library \"{{name}}\""
    }
   ]
  }
 ]
}